# SPDX-FileCopyrightText: 2014, microg Project Team
# SPDX-License-Identifier: CC0-1.0

jobs:
  include:
    - name: "Build"
      language: java
      script:
        - export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx2048m"
        - export TERM=dumb
        - ./gradlew build
    - name: "REUSE lint"
      language: minimal
      script:
        - docker pull fsfe/reuse:latest
        - docker run -v ${TRAVIS_BUILD_DIR}:/data fsfe/reuse:latest lint
